### ISSUE TITLE
panic on prune

### ISSUE THREAD

**Issue by bjo81** [rustic-rs/rustic_core#239] opened 2024-08-10 21:58 UTC
Hi,
thanks for #235 , got a new crash now:

```
name = "rustic-rs"
operating_system = "Arch Linux [64-bit]"
crate_version = "0.7.0-dev"
explanation = """
Panic occurred in file '/data/build/.cargo/git/checkouts/rustic_core-fa42f42e094d79df/1cecce8/crates/core/src/blob/tree.rs' at line 690
"""
cause = 'called `Result::unwrap()` on an `Err` value: "SendError(..)"'
method = "Panic"
backtrace = """

   0: 0x61ebd4d5e1da - <unresolved>
   1: 0x61ebd4d5b7c7 - <unresolved>
   2: 0x61ebd4ffa9cb - <unresolved>
   3: 0x7335ac51839d - <unresolved>
   4: 0x7335ac59d49c - <unresolved>
   5:        0x0 - <unresolved>"""
```

**Comment by zhuxiujia** [comment] 2024-08-15 07:19
code have many `.unwrap();` on 45 matches  on 15 files.
I suggest the author should handle these possible exceptions，may make it more stable

**Comment by simonsan** [comment] 2024-10-09 16:16
Closing as duplicate of https://github.com/rustic-rs/rustic_core/issues/209

**Closed by simonsan** 2024-10-09 16:16 UTC
Labels: A-errors, C-bug, S-triage, I-panic
